### ISSUE TITLE
having issue with audio segment determination with $number$ 

### ISSUE THREAD

**Issue by invisiblecoder99** [bobowo580/testRepo#2]
https://pastebin.com/TqRsHZ0W

 if you could update so it fetch audio plus video that would be helpful. right now video work but not audio

**Comment by invisiblecoder99** [comment]
@bobowo580  any help I can expect from you ??

**Comment by bobowo580** [comment]
> https://pastebin.com/TqRsHZ0W
> 
> if you could update so it fetch audio plus video that would be helpful. right now video work but not audio

fixed， now it can fetch both video and audio
